name: bbloc_generator
description: generator package for bloc
version: 0.1.0
author: ayalma (Ali Mohammadi) <alimohammadi7117@gmail.com>
homepage: https://github.com/ayalma/bloc

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  build: ^1.2.1
  source_gen: ^0.9.4+6
  code_builder: ^3.2.0
  analyzer: ^0.39.1
  meta: ^1.1.7
  dart_style: ^1.3.3
  bbloc:
    path: ../bbloc


dev_dependencies:
  build_test: ^0.10.0
  build_runner: ^1.7.1
  test: ^1.0.0
  bbloc:
    path: ../bbloc

