name: bbloc_generator
description: generator package for bbloc packages , that support Bind,BlocSink,BlocStream,SinkBind and EvetStream annotation of bbloc package
version: 0.3.1
homepage: https://github.com/ayalma/bloc

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  build: ">=1.3.0 <=1.6.3"
  source_gen: ">=0.9.0 <=1.0.0"
  code_builder: ^3.6.0
  analyzer: ">=0.34.2 <=0.40.4"
  meta: ^1.2.4
  dart_style: ">=1.0.0 <=1.3.11"
  bbloc: ^0.2.1


dev_dependencies:
  build_test: ^1.3.5
  build_runner: ^1.11.1
  test: ^1.15.7


