targets:
  $default:
    builders:
      bloc_generator|bloc:
        enabled: true

builders:
  todo_reporter:
    target: ":bloc_generator"
    import: "package:built_bloc_generator/bloc_generator.dart"
    builder_factories: ["blocGenerator"]
    build_extensions: {".dart": [".bloc.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]