name: bbloc
description: Fluttr package for build bloc boilerplate code with dart source generation , Bind,BlocSink,BlocStream,SinkBind and EventStream
version: 0.2.1
homepage: https://github.com/ayalma/bloc

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.2.4

dev_dependencies:
  test: 1.15.7
