name: bbloc
description: Fluttr package for build bloc boilerplate code with dart source generation , Bind,BlocSink,BlocStream,SinkBind and EventStream
version: 0.1.1
author: ayalma (Ali Mohammadi) <alimohammadi7117@gmail.com>
homepage: https://github.com/ayalma/bloc

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.7

dev_dependencies:
  test: 1.3.4
